# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ジャンル')),
                ('basic_rate', models.IntegerField(default=0, verbose_name='基本料金')),
                ('min_basic_rate_apply_amount', models.SmallIntegerField(default=0, verbose_name='基本料金適用最低時間')),
                ('max_basic_rate_apply_amount', models.SmallIntegerField(default=744, verbose_name='基本料金適用最高時間')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LessonRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended_date', models.DateField(db_index=True, verbose_name='受講日')),
                ('school_hours', models.SmallIntegerField(verbose_name='受講時間（h）')),
                ('payments', models.IntegerField(verbose_name='支払い金額')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schooladmin.Genre', verbose_name='ジャンル')),
            ],
        ),
        migrations.CreateModel(
            name='MaterRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_by_hour', models.IntegerField(default=0, verbose_name='従量料金')),
                ('min_mater_rate_apply_amount', models.SmallIntegerField(default=0, verbose_name='従量料金適用最低時間')),
                ('max_mater_rate_apply_amount', models.SmallIntegerField(default=744, verbose_name='従量料金適用最高時間')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schooladmin.Genre', verbose_name='ジャンル')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('sex', models.CharField(max_length=1, verbose_name='性別')),
                ('age', models.SmallIntegerField(verbose_name='年齢')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='lessonrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schooladmin.User', verbose_name='顧客名'),
        ),
    ]
